---
- hosts: localhost
  tasks:
    - name: Download App Server
      maven_artifact:
        group_id: org.wildfly
        artifact_id: wildfly-dist
        version: 8.1.0.Final
        extension: tar.gz
        dest: /tmp/wildfly-dist.tar.gz
    - name: Download Blue Button Data Server WAR
      maven_artifact:
        # FIXME: Once the Blue Button CI server is available again, grab an actual bluebutton-server WAR.
        group_id: org.apache.wicket
        artifact_id: wicket-examples
        version: 7.2.0
        extension: war
        dest: /tmp/bluebutton-data-server.war
    - name: Install Java
      apt:
        name: openjdk-8-jdk
      become: true

- hosts: docker_container
  tasks:
    - name: Apply Ansible Role
      include_role:
        name: karlmdavis.bluebutton_data_server
      vars:
        data_server_artifacts_mode: local
        data_server_appserver_installer_name: wildfly-dist.tar.gz
        data_server_appserver_name: wildfly-8.1.0.Final
        data_server_appserver_local_dir: /tmp
        data_server_war_name: bluebutton-data-server.war
        data_server_war_local_dir: /tmp
        data_server_ssl_server_common_name: localhost
        data_server_ssl_clients:
          - alias: bluebutton_consumers
            certificate: "{{ lookup('file', 'files/client-foo.crt.pem') }}"
        data_server_db_url: 'jdbc:hsqldb:mem:test'
        data_server_db_username: ""
        data_server_db_password: ""

